name: Unit tests

defaults:
  run:
    shell: bash -le {0}

on:
  push:
  repository_dispatch:
  workflow_dispatch:

env:
  CUDA_DEVICE_ORDER: PCI_BUS_ID

jobs:
  test:
    runs-on: [ self-hosted ]
    container:
      image: 10.0.13.31:5000/modelcloud/gptqmodel:github-ci-v5
      volumes:
        - /home/ci/models:/monster/data/model
        - /home/ci/models/huggingface:/github/home/.cache/huggingface
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: 'pip'

      - name: install requirements
        run: pip install parameterized pytest

      - name: install
        run: pip install .

      - name: test_pad_token
        run: pytest tests/test_pad_token.py

      - name: test_tokenicer_forward
        run: pytest tests/test_tokenicer_forward.py
